# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ytmp3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(654, 522)
        self.URL_label = QtWidgets.QLabel(Form)
        self.URL_label.setGeometry(QtCore.QRect(210, 80, 271, 61))
        self.URL_label.setObjectName("URL_label")
        self.File_label = QtWidgets.QLabel(Form)
        self.File_label.setGeometry(QtCore.QRect(220, 230, 231, 61))
        self.File_label.setObjectName("File_label")
        self.URL_input = QtWidgets.QLineEdit(Form)
        self.URL_input.setGeometry(QtCore.QRect(90, 140, 471, 41))
        self.URL_input.setObjectName("URL_input")
        self.Filename_input = QtWidgets.QLineEdit(Form)
        self.Filename_input.setGeometry(QtCore.QRect(90, 290, 471, 41))
        self.Filename_input.setObjectName("Filename_input")
        self.Transform_button = QtWidgets.QPushButton(Form)
        self.Transform_button.setGeometry(QtCore.QRect(230, 390, 191, 51))
        self.Transform_button.setObjectName("Transform_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.URL_label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:22pt;\">Input video URL</span></p></body></html>"))
        self.File_label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:22pt;\">Input file name</span></p></body></html>"))
        self.Transform_button.setText(_translate("Form", "Transform"))
